name: Enforce develop-only merges to main

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from develop
        run: |
          echo "PR source: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "❌ Only pull requests from 'develop' can be merged into 'main'."
            exit 1
          else
            echo "✅ Merge from develop is allowed."
          fi
