name: Enforce Conventional Commits

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  lint-commits:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch PR commits
        run: git fetch origin main --depth=1

      - name: Lint PR commit messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js
